DogBreederCapstone/DogBreederCapstone/Models/Breeder.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace DogBreederCapstone.Models
{
    public class Breeder
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        public string EmailAddress { get; set; }

        [ForeignKey("ApplicationUser")]
        public string ApplicationId { get; set; }
        public ApplicationUser ApplicationUser { get; set; }


    }
}

DogBreederCapstone/DogBreederCapstone/Controllers/BreedersController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using DogBreederCapstone.Models;
using DogBreederCapstone.Utilities;
using Microsoft.AspNet.Identity;
using SendGrid;
using SendGrid.Helpers.Mail;

namespace DogBreederCapstone.Controllers
{
    public class BreedersController : Controller
    {
        private ApplicationDbContext context;

        public BreedersController()
        {
            context = new ApplicationDbContext();
        }

        //Breeder
        public ActionResult New()
        {
            Breeder breeder = new Breeder();
            return View("BreederForm", breeder);
        }

        public ActionResult Save(Breeder breeder)
        {
            if (breeder.Id == 0)
            {
                breeder.ApplicationId = User.Identity.GetUserId();
                breeder.EmailAddress = GetUserEmail();
                context.Breeders.Add(breeder);
            }

            context.SaveChanges();
            return RedirectToAction("Index", "Litters");
        }

        private string GetUserEmail()
        {
            var applicationId = User.Identity.GetUserId();
            var applicationUser = context.Users.FirstOrDefault(u => u.Id == applicationId);
            var email = applicationUser.Email;

            return email;
        }

        //ApplicationForm
        [Authorize(Roles = RoleName.Breeder)]
        public ActionResult GetApplicationForms()
        {
            var unconfirmedApplications = context.ApplicationForms.Where(a => a.Confirmed == false)
                .Include("PotentialOwner").ToList();

            return View("UnconfirmedApplicationList", unconfirmedApplications);
        }

        [Authorize(Roles = RoleName.Breeder)]
        public ActionResult ApplicationDetails(ApplicationForm applicationForm)
        {
            ApplicationForm applicationFormFromDb = context.ApplicationForms
                .Include("PotentialOwner").FirstOrDefault(a => a.Id == applicationForm.Id);

            return View(applicationFormFromDb);
        }

        [Authorize(Roles = RoleName.Breeder)]
        public async Task<ActionResult> ConfirmApplication(ApplicationForm applicationForm)
        {
            ApplicationForm applicationFromDb =
                context.ApplicationForms.FirstOrDefault(a => a.Id == applicationForm.Id);
            applicationFromDb.Confirmed = true;
            context.SaveChanges();
            await ApplicationEmail(applicationForm.PotentialOwnerId, "yes");
            return RedirectToAction("GetApplicationForms");
        }

        [Authorize(Roles = RoleName.Breeder)]
        public async Task<ActionResult> DenyApplication(ApplicationForm applicationForm)
        {
            ApplicationForm applicationFromDb =
                context.ApplicationForms.FirstOrDefault(a => a.Id == applicationForm.Id);
            await ApplicationEmail(applicationForm.PotentialOwnerId, "no");

            context.ApplicationForms.Remove(applicationFromDb);
            context.SaveChanges();
            return RedirectToAction("GetApplicationForms");
        }

        public async Task ApplicationEmail(int? id, string confirmation)
        {
            PotentialOwner potentialOwner = context.PotentialOwners.FirstOrDefault(p => p.Id == id);
            var breeder = context.Breeders.FirstOrDefault();
            var subjectTitle = "Application Denied";
            var text = "<strong>" + Email.ApplicationDenied + "</strong>";

            if (confirmation == "yes")
            {
                subjectTitle = "Application Confirmed";
                text = "<strong>" + Email.ApplicationConfirmed + "</strong>";
            }

            var client = new SendGridClient(ApiKey.ApiKey.SendGrid);
            var from = new EmailAddress(breeder.EmailAddress, breeder.FirstName);
            var subject = subjectTitle;
            var to = new EmailAddress(potentialOwner.EmailAddress, potentialOwner.FirstName);
            var plainTextContent = text;
            var htmlContent = text;
            var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
            var response = await client.SendEmailAsync(msg);
        }

        //Appointment
        [Authorize(Roles = RoleName.Breeder)]
        public ActionResult GetAppointments()
        {
            var unconfirmedAppointments = context.Appointments.Where(a => a.Confirmed == false)
                .Include("PotentialOwner").ToList();

            return View("UnconfirmedAppointments", unconfirmedAppointments);
        }

        [Authorize(Roles = RoleName.Breeder)]
        public async Task<ActionResult> ConfirmAppointment(Appointment appointment)
        {
            Appointment appointmentFromDb = context.Appointments.FirstOrDefault(a => a.Id == appointment.Id);
            appointmentFromDb.Confirmed = true;
            context.SaveChanges();
            await AppointmentEmail(appointment.PotentialOwnerId, "yes");
            return RedirectToAction("GetAppointments");
        }

        [Authorize(Roles = RoleName.Breeder)]
        public async Task<ActionResult> DenyAppointment(Appointment appointment)
        {
            Appointment appointmentFromDb = context.Appointments.FirstOrDefault(a => a.Id == appointment.Id);
            await AppointmentEmail(appointment.PotentialOwnerId, "no");
            context.Appointments.Remove(appointmentFromDb);
            context.SaveChanges();
            return RedirectToAction("GetAppointments");
        }

        public async Task AppointmentEmail(int? id, string confirmation)
        {
            PotentialOwner potentialOwner = context.PotentialOwners.FirstOrDefault(p => p.Id == id);
            var breeder = context.Breeders.FirstOrDefault();
            var subjectTitle = "Appointment Denied";
            var text = "<strong>" + Email.AppointmentDenied + "</strong>";

            if (confirmation == "yes")
            {
                subjectTitle = "Appointment Confirmed";
                text = "<strong>" + breeder.FirstName + Email.AppointmentConfirmed + "</strong>";
            }

            var client = new SendGridClient(ApiKey.ApiKey.SendGrid);
            var from = new EmailAddress(breeder.EmailAddress, breeder.FirstName);
            var subject = subjectTitle;
            var to = new EmailAddress(potentialOwner.EmailAddress, potentialOwner.FirstName);
            var plainTextContent = text;
            var htmlContent = text;
            var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
            var response = await client.SendEmailAsync(msg);
        }


        //UpgradeOwner
        [Authorize(Roles = RoleName.Breeder)]
        public ActionResult GetDogsWithOwner()
        {
            var dogsWithOwners = context.Dogs.Where(d => d.isReserved)
                .Include(d => d.Litter)
                .Include(d => d.Collar)
                .Include(d => d.Gender)
                .Include(d => d.Image)
                .Include(d => d.PotentialOwner)
                .ToList();

            if (dogsWithOwners.Count == 0)
            {
                return View("ReservationList", dogsWithOwners);
            }

            List<Dog> dogsRefinedList = new List<Dog>();

            foreach (var dog in dogsWithOwners)
            {
                PotentialOwner owner = context.PotentialOwners.FirstOrDefault(p => p.Id == dog.PotentialOwnerId);
                if (!owner.IsOwner)
                {
                    dogsRefinedList.Add(dog);
                }
            }

            return View("ReservationList", dogsRefinedList);
        }

        [Authorize(Roles = RoleName.Breeder)]
        public ActionResult UpgradePotentialOwner(int? id)
        {
            PotentialOwner potentialOwner = context.PotentialOwners.FirstOrDefault(p => p.Id == id);
            potentialOwner.IsOwner = true;

            ApplicationForm form =
                context.ApplicationForms.FirstOrDefault(f => f.PotentialOwnerId == potentialOwner.Id);
            context.ApplicationForms.Remove(form);
            context.SaveChanges();
            return RedirectToAction("GetDogsWithOwner");
        }

        [Authorize(Roles = RoleName.Breeder)]
        public ActionResult DeclineReservation(int? id)
        {
            Dog dogFromDb = context.Dogs.FirstOrDefault(d => d.Id == id);
            ApplicationForm form =
                context.ApplicationForms.FirstOrDefault(f => f.PotentialOwnerId == dogFromDb.PotentialOwnerId);
            context.ApplicationForms.Remove(form);
            dogFromDb.PotentialOwnerId = null;
            dogFromDb.isReserved = false;
            context.SaveChanges();
            return RedirectToAction("GetDogsWithOwner");
        }


        //NotifyOwnersWatchingLitter
        public async Task<ActionResult> NotifyWatchingOwners(int? id)
        {
            var potentialOwnersWatchingLitter = context.PotentialOwners.Where(p => p.WatchedLitterId == id).ToList();

            if (potentialOwnersWatchingLitter.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            foreach (var potentialOwner in potentialOwnersWatchingLitter)
            {
                await SendLitterUpdateEmail(potentialOwner);
            }

            return RedirectToAction("Index", "Home");
        }

        public async Task SendLitterUpdateEmail(PotentialOwner potentialOwner)
        {
            var breeder = context.Breeders.FirstOrDefault();
            var client = new SendGridClient(ApiKey.ApiKey.SendGrid);
            var from = new EmailAddress(breeder.EmailAddress, breeder.FirstName);
            var subject = "Litter Update!";
            var to = new EmailAddress(potentialOwner.EmailAddress, potentialOwner.FirstName);

DogBreederCapstone/DogBreederCapstone/Views/Breeders/ApplicationDetails.cshtml
@model DogBreederCapstone.Models.ApplicationForm

@{
    ViewBag.Title = "ApplicationDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<style>
    div.col-container {
        display: table;
        width: 100%;
    }

    div.col-md-3 {
        text-align: right;
        padding-bottom: 2px;
        display: table-cell;
        height: 70px;
    }

    div.col-md-9 {
        padding-bottom: 5px;
        text-indent: 50px;
        display: table-cell;
        height: 70px;
    }

    div.left {
        text-align: left;
    }

    div.right {
        text-align: right;
    }

    div.bottom-padding {
        padding-bottom: 25px;
    }

    hr.border {
        border: 5px outset #B2D7F7;
        border-radius: 2.5px;
    }
</style>

<br/>
<h2 style="text-align: center">Application Review</h2>

<hr class="border"/>

<div class="col-container">
    <div class="col-md-2 right">
        <dt>
            @Html.DisplayNameFor(model => model.PotentialOwner.FirstName)
        </dt>
    </div>
    <div class="col-md-2 left">
        <dd>
            @Html.DisplayFor(model => model.PotentialOwner.FirstName)
        </dd>
    </div>
    <div class="col-md-2 right">
        <dt>
            @Html.DisplayNameFor(model => model.FamilyName)
        </dt>
    </div>
    <div class="col-md-2 left">
        <dd>
            @Html.DisplayFor(model => model.FamilyName)
        </dd>
    </div>
    <div class="col-md-2 right">
        <dt>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>
    </div>
    <div class="col-md-2 left">
        <dd>
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>
    </div>
    <div class="col-md-2 right">
        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
    </div>
    <div class="col-md-10 left bottom-padding">
        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </div>
    

    <div class="col-md-2 right">
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
    </div>
    <div class="col-md-2 left">
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
    </div>
    <div class="col-md-2 right">
        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>
    </div>
    <div class="col-md-2 left">
        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>
    </div>
    <div class="col-md-2 right">
        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>
    </div>
    <div class="col-md-2 left">
        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>
    </div>
    <div class="col-md-2 right">
        <dt>
            @Html.DisplayNameFor(model => model.Zipcode)
        </dt>
    </div>
    <div class="col-md-10 left bottom-padding">
        <dd>
            @Html.DisplayFor(model => model.Zipcode)
        </dd>
    </div>
    
    <hr class="border"/>

    <div class="col-md-6 bottom-padding">
        <dt>
            @Html.DisplayNameFor(model => model.Referral)
        </dt>
    </div>
    <div class="col-md-6 bottom-padding">
        <dd>
            @Html.DisplayFor(model => model.Referral)
        </dd>
    </div>
    <div class="col-md-6 bottom-padding">
        <dt>
            @Html.DisplayNameFor(model => model.Use)
        </dt>
    </div>
    <div class="col-md-6 bottom-padding">
        <dd>
            @Html.DisplayFor(model => model.Use)
        </dd>
    </div>
    <div class="col-md-6 bottom-padding">
        <dt>
            @Html.DisplayNameFor(model => model.Live)
        </dt>
    </div>
    <div class="col-md-6 bottom-padding">
        <dd>
            @Html.DisplayFor(model => model.Live)
        </dd>
    </div>
    <div class="col-md-6 bottom-padding">
        <dt>
            @Html.DisplayNameFor(model => model.Training)
        </dt>
    </div>
    <div class="col-md-6 bottom-padding">
        <dd>
            @Html.DisplayFor(model => model.Training)
        </dd>
    </div>
    <div class="col-md-6 bottom-padding">
        <dt>
            @Html.DisplayNameFor(model => model.PreviousDogs)
        </dt>
    </div>
    <div class="col-md-6 bottom-padding">
        <dd>
            @Html.DisplayFor(model => model.PreviousDogs)
        </dd>
    </div>
    <div class="col-md-6 bottom-padding">
        <dt>
            @Html.DisplayNameFor(model => model.PreviousDogsLive)
        </dt>
    </div>
    <div class="col-md-6 bottom-padding">
        <dd>
            @Html.DisplayFor(model => model.PreviousDogsLive)
        </dd>
    </div>
    <div class="col-md-6 bottom-padding">
        <dt>
            @Html.DisplayNameFor(model => model.OutOfTownPlan)
        </dt>
    </div>
    <div class="col-md-6 bottom-padding">
        <dd>
            @Html.DisplayFor(model => model.OutOfTownPlan)
        </dd>
    </div>
    <div class="col-md-6 bottom-padding">
        <dt>
            @Html.DisplayNameFor(model => model.Children)
        </dt>
    </div>
    <div class="col-md-6 bottom-padding">
        <dd>
            @Html.DisplayFor(model => model.Children)
        </dd>
    </div>
    <div class="col-md-6 bottom-padding">
        <dt>
            @Html.DisplayNameFor(model => model.Fence)
        </dt>
    </div>
    <div class="col-md-6 bottom-padding">
        <dd>
            @Html.DisplayFor(model => model.Fence)
        </dd>
    </div>
    <div class="col-md-6 bottom-padding">
        <dt>
            @Html.DisplayNameFor(model => model.Reasoning)
        </dt>
    </div>
    <div class="col-md-6 bottom-padding">
        <dd>
            @Html.DisplayFor(model => model.Reasoning)
        </dd>
    </div>
    <div class="col-md-6 bottom-padding">
        <dt>
            @Html.DisplayNameFor(model => model.Allergies)
        </dt>
    </div>
    <div class="col-md-6 bottom-padding">
        <dd>
            @Html.DisplayFor(model => model.Allergies)
        </dd>
    </div>
    <div class="col-md-6 bottom-padding">
        <dt>
            @Html.DisplayNameFor(model => model.LeftAlone)
        </dt>
    </div>
    <div class="col-md-6 bottom-padding">
        <dd>
            @Html.DisplayFor(model => model.LeftAlone)
        </dd>
    </div>
</div>

<hr class="border"/>

<p style="text-align: center">
    <input type="button" class="btn btn-sm" value="Accept" onclick="location.href = '@Url.Action("ConfirmApplication","Breeders", Model)'" />
    <input type="button" class="btn btn-sm" value="Deny" onclick="location.href = '@Url.Action("DenyApplication","Breeders", Model)'" />
</p>

DogBreederCapstone/DogBreederCapstone/Views/Breeders/BreederForm.cshtml
@model DogBreederCapstone.Models.Breeder

@{
    ViewBag.Title = "BreederForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Breeder Form</h2>

@using (Html.BeginForm("Save", "Breeders"))
{
    <div class="form-group">
        @Html.LabelFor(m => m.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
    </div>
    @Html.HiddenFor(m => m.Id);
    <button type="submit" class="btn btn-primary">Finish</button>
}

DogBreederCapstone/DogBreederCapstone/Views/Breeders/ReservationList.cshtml
@model IEnumerable<DogBreederCapstone.Models.Dog>

@{
    ViewBag.Title = "ReservationList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .well {
        height: 60px;
        width: auto;
        margin-left: 5.5%;
        margin-right: 5.5%;
        background-color: #c9edff;
        text-align: center;
        padding-top: 20px;
        color: black;
        border: 1px solid #eee;
        box-shadow: 0 2px 2px #ccc;
        font-family: Trebuchet MS, Helvetica, sans-serif;
    }

    h5 {
        font-style: oblique;
        font-weight: bold;
        font-size: medium;
    }

    .btn-sm:hover {
        background-color: #19334d;
    }


    hr.border {
        border: 4px outset #c9edff;
        border-radius: 2.5px;
    }

    hr.border-sm {
        border: 1px solid #c9edff;
        box-shadow: 0 2px 2px #19334d;
        border-radius: 2.5px;
    }

    #table {
        font-weight: bold;
        width: 100%;
    }

    #table td, #table th {
      border: 0.20px inset #eee/*#19334d*/;
      box-shadow: 0 2px 2px #ccc;
      padding: 8px;
      text-align: center;
    }

    #table tr:nth-child(even){background-color: #ecf2f9;}

    #table tr:hover {background-color: #ccc; color: #19334d;}

    #table th {
      padding-top: 12px;
      padding-bottom: 12px;
      text-align: center;
      background-color: #19334d;
      color: #eee;
    }

</style>

<br />
<div>
    <h2 style="text-align: center;">Reservations</h2>
    <hr class="border" />
    <h5 class="well">~reservations that are awaiting your response</h5>
    <hr class="border-sm" />
</div>

<table id="table">
    <thead>
        <tr>
            <th>Pup</th>
            <th>Owner Name</th>
            <th>Litter</th>
            <th>Upgrade User</th>
            <th>Decline</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            var fullName = item.PotentialOwner.FirstName + " " + item.PotentialOwner.LastName;
            <tr>
                <td>
                    <img src="@Url.Content(item.Image.ImagePath)" alt="Image" style="width: 125px; height: 100px;" />
                </td>
                <td>
                    @fullName
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Litter.Name)
                </td>
                <td>
                    <input type="button" class="btn btn-sm" value="Approve & Upgrade" onclick="location.href = '@Url.Action("UpgradePotentialOwner", "Breeders", new {id = item.PotentialOwnerId}, null)'" />
                </td>
                <td>
                    <input type="button" class="btn btn-sm" value="Decline" onclick="location.href = '@Url.Action("DeclineReservation", "Breeders", new {id = item.Id}, null)'" />
                </td>
            </tr>
        }
    </tbody>
</table>
<hr class="border-sm" />

DogBreederCapstone/DogBreederCapstone/Views/Breeders/UnconfirmedApplicationList.cshtml
@model IEnumerable<DogBreederCapstone.Models.ApplicationForm>

@{
    ViewBag.Title = "UnconfirmedApplicationList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .well {
        height: 60px;
        width: auto;
        margin-left: 5.5%;
        margin-right: 5.5%;
        background-color: #c9edff;
        text-align: center;
        padding-top: 20px;
        color: black;
        border: 1px solid #eee;
        box-shadow: 0 2px 2px #ccc;
        font-family: Trebuchet MS, Helvetica, sans-serif;
    }

    h5 {
        font-style: oblique;
        font-weight: bold;
        font-size: medium;
    }

    .btn-sm:hover {
        background-color: #19334d;
    }

    hr.border {
        border: 4px outset #c9edff;
        border-radius: 2.5px;
    }

    hr.border-sm {
        border: 1px solid #c9edff;
        box-shadow: 0 2px 2px #19334d;
        border-radius: 2.5px;
    }

    #table {
        font-weight: bold;
        width: 100%;
    }

    #table td, #table th {
      border: 0.20px inset #eee/*#19334d*/;
      box-shadow: 0 2px 2px #ccc;
      padding: 8px;
      text-align: center;
    }

    #table tr:nth-child(even){background-color: #ecf2f9;}

    #table tr:hover {background-color: #ccc; color: #19334d;}

    #table th {
      padding-top: 12px;
      padding-bottom: 12px;
      text-align: center;
      background-color: #19334d;
      color: #eee;
    }

</style>

<br />
<div>
    <h2 style="text-align: center;">Applications</h2>
    <hr class="border" />
    <h5 class="well">~applications that are awaiting your request</h5>
    <hr class="border-sm" />
</div>

<table id="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PotentialOwner.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FamilyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th>Review</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PotentialOwner.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FamilyName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.State)
                </td>
                <td>
                    <input type="button" class="btn btn-sm" value="Review" onclick="location.href = '@Url.Action("ApplicationDetails", "Breeders", item)'" />
                </td>
            </tr>
        }
    </tbody>
</table>
<hr class="border-sm" />

DogBreederCapstone/DogBreederCapstone/Views/Breeders/UnconfirmedAppointments.cshtml
@model IEnumerable<DogBreederCapstone.Models.Appointment>

@{
    ViewBag.Title = "UnconfirmedAppointments";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .well {
        height: 60px;
        width: auto;
        margin-left: 5.5%;
        margin-right: 5.5%;
        background-color: #c9edff;
        text-align: center;
        padding-top: 20px;
        color: black;
        border: 1px solid #eee;
        box-shadow: 0 2px 2px #ccc;
        font-family: Trebuchet MS, Helvetica, sans-serif;
    }

    hr.border {
        border: 4px outset #c9edff;
        border-radius: 2.5px;
    }

    hr.border-sm {
        border: 1px solid #c9edff;
        box-shadow: 0 2px 2px #19334d;
        border-radius: 2.5px;
    }

    #table {
        font-weight: bold;
        width: 100%;
    }

    #table td, #table th {
      border: 0.20px inset #eee/*#19334d*/;
      box-shadow: 0 2px 2px #ccc;
      padding: 8px;
      text-align: center;
    }

    #table tr:nth-child(even){background-color: #ecf2f9;}

    #table tr:hover {background-color: #ccc; color: #19334d;}

    #table th {
      padding-top: 12px;
      padding-bottom: 12px;
      text-align: center;
      background-color: #19334d;
      color: #eee;
    }


    h5 {
        font-style: oblique;
        font-weight: bold;
        font-size: medium;
    }

    .btn-sm:hover {
        background-color: #19334d;
    }
</style>

<br />
<div>
    <h2 style="text-align: center;">Appointments</h2>
    <hr class="border" />
    <h5 class="well">~ Appointments that are awaiting your request</h5>
    <hr class="border-sm" />
</div>

<table id="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PotentialOwner.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Reason)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th>Confirm/Deny</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PotentialOwner.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Reason)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Time)
            </td>
            <td>
                <input type="button" class="btn btn-sm" value="Confirm" onclick="location.href = '@Url.Action("ConfirmAppointment","Breeders", item)'" />
                <input type="button" class="btn btn-sm" value="Deny" onclick="location.href = '@Url.Action("DenyAppointment","Breeders", item)'" />
            </td>
        </tr>
    }

</table>
<hr class="border-sm" />