DogBreederCapstone/DogBreederCapstone/Models/Dog.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Drawing;
using System.Linq;
using System.Web;

namespace DogBreederCapstone.Models
{
    public class Dog
    {
        [Key]
        public int Id { get; set; }

        public Litter Litter { get; set; }
        [Display(Name = "Litter")]
        public int LitterId { get; set; }

        public Gender Gender { get; set; }
        [Display(Name = "Gender")]
        public int GenderId { get; set; }

        public Collar Collar { get; set; }
        [Display(Name = "Puppy Collar")]
        public int CollarId { get; set; }
    
        public Image Image { get; set; }
        [Display(Name = "Image")]
        public int? ImageId { get; set; }

        public PotentialOwner PotentialOwner { get; set; }
        [Display(Name = "Owner")]
        public int? PotentialOwnerId { get; set; }

        public bool isReserved { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }
    }
}

DogBreederCapstone/DogBreederCapstone/Controllers/Api/DogsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;
using AutoMapper;
using DogBreederCapstone.Dtos;
using DogBreederCapstone.Models;

namespace DogBreederCapstone.Controllers.Api
{
    public class DogsController : ApiController
    {
        private ApplicationDbContext context;

        public DogsController()
        {
            context = new ApplicationDbContext();
        }

        // GET api/dogs
        public IHttpActionResult GetDogs()
        {
            var dogsFromDb = context.Dogs
                .Include(d => d.Collar)
                .Include(d => d.Gender)
                .Include(d => d.Litter)
                .ToList()
                .Select(Mapper.Map<Dog, DogDto>);

            return Ok(dogsFromDb);
        }

        // GET api/dogs/5
        public IHttpActionResult GetDog(int id)
        {
            var dogFromDb = context.Dogs.FirstOrDefault(d => d.Id == id);

            if (dogFromDb == null)
            {
                return NotFound();
            }

            return Ok(Mapper.Map<Dog, DogDto>(dogFromDb));
        }

        // POST api/dogs
        [System.Web.Http.HttpPost]
        public IHttpActionResult CreateDog(DogDto dogDto)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            var dog = Mapper.Map<DogDto, Dog>(dogDto);
            context.Dogs.Add(dog);
            context.SaveChanges();

            dogDto.Id = dog.Id;

            return Created(new Uri(Request.RequestUri + "/" + dog.Id), dogDto);
        }

        // PUT api/dogs/5
        public IHttpActionResult UpdateDog(int id, DogDto dogDto)
        {
            if (!ModelState.IsValid)
            {
                throw new HttpResponseException(HttpStatusCode.BadRequest);
            }

            var dogFromDb = context.Dogs.FirstOrDefault(d => d.Id == id);

            if (dogFromDb == null)
            {
                throw new HttpResponseException(HttpStatusCode.NotFound);
            }

            Mapper.Map(dogDto, dogFromDb);

            context.SaveChanges();
            return Ok();
        }

        // DELETE api/dogs/5
        [System.Web.Http.HttpDelete]
        public IHttpActionResult DeleteDog(int id)
        {
            var dogFromDb = context.Dogs.FirstOrDefault(d => d.Id == id);

            if (dogFromDb == null)
            {
                throw new HttpResponseException(HttpStatusCode.NotFound);
            }

            context.Dogs.Remove(dogFromDb);
            context.SaveChanges();
            return Ok();
        }
    }
}

DogBreederCapstone/DogBreederCapstone/Controllers/DogsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using DogBreederCapstone.Models;
using DogBreederCapstone.Utilities;
using DogBreederCapstone.ViewModels;
using Microsoft.AspNet.Identity;
using SendGrid;
using SendGrid.Helpers.Mail;

namespace DogBreederCapstone.Controllers
{
    public class DogsController : Controller
    {
        private ApplicationDbContext context;

        public DogsController()
        {
            context = new ApplicationDbContext();
        }

        [AllowAnonymous]
        public ActionResult Index()
        {
            var dogsFromDb = context.Dogs
                .Include(d => d.Collar)
                .Include(d => d.Gender)
                .Include(d => d.Litter)
                .Include(d => d.Image)
                .ToList();

            if (User.IsInRole(RoleName.Breeder))
            {
                return View("List", dogsFromDb);
            }

            return View("ReadOnlyList", dogsFromDb);
        }

        public ActionResult GetDogs(int? id)
        {
            var dogsFromDb = context.Dogs.Where(d => d.LitterId == id)
                .Include(d => d.Litter)
                .Include(d => d.Collar)
                .Include(d => d.Gender)
                .Include(d => d.Image)
                .ToList();
            return View("ReadOnlyList", dogsFromDb);
        }

        [Authorize(Roles = RoleName.Breeder)]
        public ActionResult New()
        {
            var genderTypes = context.Genders.ToList();
            var collarTypes = context.Collars.ToList();
            var litterOptions = context.Litters.ToList();
            var imageOptions = context.Images.ToList();

            DogFormViewModel viewModel = new DogFormViewModel
            {
                Litters = litterOptions,
                Genders = genderTypes,
                Collars = collarTypes,
                Images = imageOptions
            };

            return View("DogForm", viewModel);
        }

        [Authorize(Roles = RoleName.Breeder)]
        public ActionResult Edit(int id)
        {
            Dog dog = context.Dogs.FirstOrDefault(l => l.Id == id);

            if (dog == null)
            {
                return HttpNotFound();
            }

            DogFormViewModel viewModel = new DogFormViewModel
            {
                Litters = context.Litters.ToList(),
                Collars =  context.Collars.ToList(),
                Genders = context.Genders.ToList(),
                Images = context.Images.ToList()
            };

            return View("DogForm", viewModel);
        }


        [HttpPost]
        [Authorize(Roles = RoleName.Breeder)]
        public ActionResult Save(Dog dog)
        {
            if (dog.Id == 0)
            {
                context.Dogs.Add(dog);
            }
            else
            {
                Dog dogFromDb = context.Dogs.FirstOrDefault(d => d.Id == dog.Id);
                dogFromDb.LitterId = dog.LitterId;
                dogFromDb.CollarId = dog.CollarId;
                dogFromDb.GenderId = dog.GenderId;
                dogFromDb.ImageId = dog.ImageId;
                dogFromDb.Description = dog.Description;
            }

            context.SaveChanges();
            return RedirectToAction("Index", "Litters");
        }

        public ActionResult Details(int? id)
        {
            Dog dogFromDb = context.Dogs
                .Include(d => d.Litter)
                .Include(d => d.Collar)
                .Include(d => d.Gender)
                .Include(d => d.Image)
                .FirstOrDefault(d => d.Id == id);

            return View(dogFromDb);
        }

        [Authorize(Roles = RoleName.PotentialOwner)]
        public async Task<ActionResult> Reserve(int? id)
        {
            var applicationId = User.Identity.GetUserId();
            PotentialOwner potentialOwner =
                context.PotentialOwners.FirstOrDefault(p => p.ApplicationId == applicationId);

            ApplicationForm form =
                context.ApplicationForms.FirstOrDefault(f => f.PotentialOwnerId == potentialOwner.Id);

            if (form == null || form.Confirmed == false)
            {
                return View("NotApproved");
            }

            Dog dog = context.Dogs.FirstOrDefault(d => d.Id == id);
            dog.isReserved = true;
            dog.PotentialOwnerId = potentialOwner.Id;

            context.SaveChanges();
            await SendReserveSpotEmail(potentialOwner);
            return View("SpotReserved");
        }

        public async Task SendReserveSpotEmail(PotentialOwner potentialOwner)
        {
            var breeder = context.Breeders.FirstOrDefault();
            var client = new SendGridClient(ApiKey.ApiKey.SendGrid);
            var from = new EmailAddress(potentialOwner.EmailAddress, potentialOwner.FirstName);
            var subject = "Spot Reserved";
            var to = new EmailAddress(breeder.EmailAddress, breeder.FirstName);
            var plainTextContent = "<strong>" + potentialOwner.FirstName + Email.SpotReserved + "</strong>";
            var htmlContent = "<strong>" + potentialOwner.FirstName + Email.SpotReserved + "</strong>";
            var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
            var response = await client.SendEmailAsync(msg);
        }
    }
}

DogBreederCapstone/DogBreederCapstone/Views/Dogs/Details.cshtml
@model DogBreederCapstone.Models.Dog

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Dog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ImageId)
        </dt>

        <dd>
            <img src="@Url.Content(Model.Image.ImagePath)" alt="Image" style="width: 250px; height: 250px;"/>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Collar.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Collar.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Litter.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Litter.Name)
        </dd>

    </dl>
</div>

DogBreederCapstone/DogBreederCapstone/Views/Dogs/DogForm.cshtml
@model DogBreederCapstone.ViewModels.DogFormViewModel

@{
    ViewBag.Title = "DogForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    hr.border {
        border: 5px outset #B2D7F7;
        border-radius: 2.5px;
    }
</style>
<br/>
<h2 style="text-align: center;">Add a New Pup</h2>
<hr class="border"/>

@using (Html.BeginForm("Save", "Dogs"))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Dog.LitterId, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.DropDownListFor(m => m.Dog.LitterId, new SelectList(Model.Litters, "Id", "Name"), "Select Litter", new { @class = "form-control col-md-6" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Dog.CollarId, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.DropDownListFor(m => m.Dog.CollarId, new SelectList(Model.Collars, "Id", "Color"), "Select Collar", new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Dog.GenderId, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.DropDownListFor(m => m.Dog.GenderId, new SelectList(Model.Genders, "Id", "Name"), "Select Gender", new { @class = "form-control col-md-6" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Dog.ImageId, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.DropDownListFor(m => m.Dog.ImageId, new SelectList(Model.Images, "Id", "Title"), "Select Image", new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Dog.Description, htmlAttributes: new { @class = "control-label col-md-2"})
        @Html.TextAreaFor(m => m.Dog.Description, new {@class = "form-control", rows="3"})
    </div>
    @Html.HiddenFor(m => m.Dog.Id)
    <div style="margin-left:50px;">
        <button type="submit" class="btn btn-sm">Add</button>
    </div>
}

DogBreederCapstone/DogBreederCapstone/Views/Dogs/List.cshtml
@model IEnumerable<DogBreederCapstone.Models.Dog>

@{
    ViewBag.Title = "Dogs";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Dogs</h2>

<table id="dogs" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Litter Name</th>
            <th>Collar Color</th>
            <th>Gender</th>
            <th>Details</th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Litter.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Collar.Color)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender.Name)
            </td>
            <td>
                @Html.ActionLink("Info", "Details", new { id = item.Id }, null)
            </td>
        </tr>
    }

    </tbody>
</table>

DogBreederCapstone/DogBreederCapstone/Views/Dogs/NotApproved.cshtml
@{
    ViewBag.Title = "NotApproved";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .well {
        height: 60px;
        width: 70%;
        background-color: #B2D7F7;
        text-align: center;
        padding-top: 2px;
        color: black;
    }
</style>

<div>
    <h2>OOPS! Your application has not been processed yet!</h2>
</div>

<div>
    <h4 class="well">Please fill out an application if you haven't done so already. If you have filled out an application please be patient as we review and process your request.</h4>
</div>
<div>
    <input type="button" class="btn btn-sm" value="Apply" onclick="location.href = '@Url.Action("NewApplicationForm","PotentialOwners")'" />
</div>
<br />
<div>
    <input type="button" class="btn btn-sm" value="Back To Litters" onclick="location.href = '@Url.Action("Index","Litters")'" />
</div>

DogBreederCapstone/DogBreederCapstone/Views/Dogs/ReadOnlyList.cshtml
@model IEnumerable<DogBreederCapstone.Models.Dog>

@{
    ViewBag.Title = "Dogs";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Dogs</h2>

<table id="dogs" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Litter Name</th>
            <th>Collar Color</th>
            <th>Gender</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Litter.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Collar.Color)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Gender.Name)
                </td>
            </tr>
        }

    </tbody>
</table>

DogBreederCapstone/DogBreederCapstone/Views/Dogs/SpotReserved.cshtml
@{
    ViewBag.Title = "SpotReserved";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div>
    <h2>Congratulations! Your spot has been reserved!</h2>
</div>
<div>
    <h4>Welcome to the family! You now have the ability to post pictures of your pup in the Owner's Forum!</h4>
</div>