DogBreederCapstone/DogBreederCapstone/Models/ForumMessage.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace DogBreederCapstone.Models
{
    public class ForumMessage
    {
        public int Id { get; set; }
        public string Status { get; set; }

        [Display(Name = "Upload File")]
        public string ImagePath { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }

    }
}

DogBreederCapstone/DogBreederCapstone/Controllers/ForumMessagesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DogBreederCapstone.Models;
using DogBreederCapstone.Utilities;
using Microsoft.AspNet.Identity;

namespace DogBreederCapstone.Controllers
{
    public class ForumMessagesController : Controller
    {
        private ApplicationDbContext context;

        public ForumMessagesController()
        {
            context = new ApplicationDbContext();
        }

        [Authorize(Roles = RoleName.BreederOrPotentialOwner)]
        public ActionResult Add()
        {
            ForumMessage message = new ForumMessage();
            return View(message);
        }

        [HttpPost]
        public ActionResult Add(ForumMessage message)
        {
            string fileName = Path.GetFileNameWithoutExtension(message.ImageFile.FileName);
            string extension = Path.GetExtension(message.ImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yy-MM-dd") + extension;
            message.ImagePath = "~/ForumImages/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/ForumImages/"), fileName);
            message.ImageFile.SaveAs(fileName);
            context.ForumMessages.Add(message);
            context.SaveChanges();
            ModelState.Clear();

            return RedirectToAction("GetForumPosts");
        }

        [HttpGet]
        [Authorize(Roles = RoleName.BreederOrPotentialOwner)]
        public ActionResult GetForumPosts()
        {
            if (User.IsInRole(RoleName.PotentialOwner))
            {
                var applicationId = User.Identity.GetUserId();
                PotentialOwner potentialOwner =
                    context.PotentialOwners.FirstOrDefault(p => p.ApplicationId == applicationId);

                if (!potentialOwner.IsOwner)
                {
                    return View("NonOwner");
                }
            }

            var gallery = context.ForumMessages.ToList();
            return View("Gallery", gallery);
        }
    }
}

DogBreederCapstone/DogBreederCapstone/Views/ForumMessages/Add.cshtml
@model DogBreederCapstone.Models.ForumMessage

@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .well {
        height: 60px;
        width: auto;
        margin-left: 5.5%;
        margin-right: 5.5%;
        background-color: #c9edff;
        text-align: center;
        padding-top: 20px;
        color: black;
        border: 1px solid #eee;
        box-shadow: 0 2px 2px #ccc;
        font-family: Trebuchet MS, Helvetica, sans-serif;

    }

    h5 {
        font-style: oblique;
        font-weight: bold;
        font-size: medium;
    }


    hr.border {
        border: 5px outset #B2D7F7;
        border-radius: 2.5px;
    }
</style>

<br />
<div>
    <h2 style="text-align:center;">Forum Post</h2>
    <hr class="border" />
    <h5 class="well">~upload an image of your Doggo to our Owner's Forum</h5>
</div>

@using (Html.BeginForm("Add", "ForumMessages", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" class="btn-sm" name="ImageFile" runat="server" required />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Post" class="btn btn-sm" />
            </div>
        </div>
    </div>
}

DogBreederCapstone/DogBreederCapstone/Views/ForumMessages/Gallery.cshtml
@model IEnumerable<DogBreederCapstone.Models.ForumMessage>

@{
    ViewBag.Title = "Gallery";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>

    .well {
        height: 60px;
        width: auto;
        margin-left: 5.5%;
        margin-right: 5.5%;
        background-color: #c9edff;
        text-align: center;
        padding-top: 20px;
        color: black;
        border: 1px solid #eee;
        box-shadow: 0 2px 2px #ccc;
        font-family: Trebuchet MS, Helvetica, sans-serif;

    }

    h2 {
        text-align: center;
        font-weight: bold;
        font-family: Trebuchet MS, Helvetica, sans-serif;
    }

    h5 {
        font-style: oblique;
        font-weight: bold;
        font-size: medium;
    }

    .btn-sm:hover {
        background-color: #19334d;
    }

    div.container {
        margin-top: 10px;
        padding: 5px;
    }

    div.gallery {
        margin: 5px;
        border: 1px solid #ccc;
        float: left;
        width: auto;
        height: auto;
        box-shadow: 0 4px 8px 0 slategray, 0 6px 20px 0 slategray;
    }

        div.gallery:hover {
            border: 1px solid #777;
        }

        div.gallery img {
            width: 33.33%;
            height: auto;
        }

    div.desc {
        padding: 15px;
        text-align: center;
        box-shadow: 0 4px 8px 0 slategray, 0 6px 20px 0 slategray;
    }

    div.right {
        text-align: center;
        padding-top: 20px;
        margin-left: 30px;
    }

    hr.border {
        border: 4px outset #c9edff;
        border-radius: 2.5px;
    }

    hr.border-sm {
        border: 1px solid #c9edff;
        box-shadow: 0 2px 2px #19334d;
        border-radius: 2.5px;
    }

    .btn-primary {
        display: block;
        width: 80%;
    }
</style>

<br />

<body>
    <div class="row">
        <h2 style="text-align: center;">Owner's Forum</h2>
        <hr class="border" />
        <h5 class="well col-md-6">~Share what you and your Doggo have been up to!</h5>
        <div class="right">
            <input type="button" class="btn btn-primary" value="Post Status" onclick="location.href = '@Url.Action("Add", "ForumMessages")'" />
        </div>
    </div>
    <hr class="border-sm" />
    <br>
    <div class="row">
        <div class="container">
            @foreach (var item in Model)
            {
                <div class="gallery">
                    <img src="@Url.Content(item.ImagePath)" alt="Image" style="width: 275px; height: 250px;" />
                    <div class="desc">@Html.DisplayFor(modelItem => item.Status)</div>
                </div>
            }

        </div>
    </div>
</body>

<hr class="border-sm" />

DogBreederCapstone/DogBreederCapstone/Views/ForumMessages/NonOwner.cshtml
@{
    ViewBag.Title = "NonOwner";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>You must become an owner to access this page.</h2>
<br />
<div>
    <input type="button" class="btn btn-sm" value="Apply for Doggo" onclick="location.href='@Url.Action("NewApplicationForm", "PotentialOwners")'" />
</div>
<div>
    <input type="button" class="btn btn-sm" value="View Litters" onclick="location.href='@Url.Action("Index", "Home")'" />
</div>